# 日志输出配置
logging:
  level:
    cc.xiaoxu.cloud: DEBUG

spring:
  datasource:
    url: jdbc:@env.api.db.type@://172.168.1.78:50003/postgres?currentSchema=public
  data:
    redis:
      host: 172.168.1.78
      port: 50002
api:
  file:
    location: /Users/x/Documents/02_code/_my/cloud/files/
  model:
    url: http://127.0.0.1:50005

knife4j:
  basic:
    enable: false