spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.5.111:5432/postgres?useUnicode=true&useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=True
    username: postgres
    password: root

# 日志输出配置
logging:
  level:
    cc.xiaoxu.cloud: DEBUG