# 日志输出配置
logging:
  level:
    cc.xiaoxu.cloud: INFO

spring:
  datasource:
    url: jdbc:@env.api.db.type@://@env.api.db.host@:@env.api.db.port@/postgres?currentSchema=public

api:
  file:
    location: /home/files/
  model:
    url: http://172.17.0.1:50004